# LIBS

In [1]:
import pandas as pd

# IMPORT

In [2]:
# dados de 2022
# 2022 data

first_path2022 = "C:\\Users\\SAMSUNG\\OneDrive\\Documentos\\PROJETO INTEGRADOR 1\\dados\\1st_2022"
second_path2022 = "C:\\Users\\SAMSUNG\\OneDrive\\Documentos\\PROJETO INTEGRADOR 1\\dados\\2nd_2022"

first_df_2022 = pd.read_csv(first_path2022, index_col=0)
second_df_2022 = pd.read_csv(first_path2022, index_col=0)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_23972\1767904495.py:7: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  first_df_2022 = pd.read_csv(first_path2022, index_col=0)
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_23972\1767904495.py:8: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  second_df_2022 = pd.read_csv(first_path2022, index_col=0)

In [3]:
''' 
PT-BR
    em analise explorativa, notou-se que algumas colunas
    mantiveram suas features, mas foram renomeadas a partir
    de 2023, gerando uma incoerências do ano de 2022 com os
    restantes:
     
    cidade de ocorrencia deixou de ser nomeada como "CIDADE"
    e passou a ser nomeada como "NOME_MUNICIPIO";

    data de registro deixou de ser nemada como
    "DATA_COMUNICACAO_BO" e passou a ser nomeada
    como "DATA_REGISTRO";

    descrição de periodo de ocorrencia deicou de ser nomeada
    como "DESCR_PERIODO" e passou a ser nomeada como
    "DESC_PERIODO".

    descrição do local de ocorrencia deixou de ser nomeada
    como "DESCR_TIPOLOCAL e passou a ser nomeada como
    "DESCR_SUBTIPOLOCAL".

EN
    in exploratory analysis, it was noted that some columns
    kept their features, but were renamed starting in 2023,
    creating inconsistencies between 2022 and the other years:

    the city of occurrence feature was no longer named "CIDADE"
    and was now named "NOME_MUNICIPIO";

    the registration date feature was no longer named
    "DATA_COMUNICACAO_BO" and was now named "DATA_REGISTRO";

    the description of the occurrence period feature was no longer
    named "DESCR_PERIODO" and was now named "DESC_PERIODO".

    the description of the occurrence location feature was no longer
    named "DESCR_TIPOLOCAL" and was now named
    "DESCR_SUBTIPOLOCAL".

'''

# renomando as colunas de 2022
# renaming 2022 columns

first_df_2022_renamed = first_df_2022.rename(columns={'CIDADE': 'NOME_MUNICIPIO',
                                                      'DATA_COMUNICACAO_BO': 'DATA_REGISTRO',
                                                      "DESCR_PERIODO": "DESC_PERIODO",
                                                      "DESCR_TIPOLOCAL": "DESCR_SUBTIPOLOCAL"})

second_df_2022_renamed = second_df_2022.rename(columns={'CIDADE': 'NOME_MUNICIPIO',
                                                      'DATA_COMUNICACAO_BO': 'DATA_REGISTRO',
                                                      "DESCR_PERIODO": "DESC_PERIODO",
                                                      "DESCR_TIPOLOCAL": "DESCR_SUBTIPOLOCAL"})

In [4]:
# dados de 2023
# 2023 data

first_path2023 = "C:\\Users\\SAMSUNG\\OneDrive\\Documentos\\PROJETO INTEGRADOR 1\\dados\\1st_2023"
second_path2023 = "C:\\Users\\SAMSUNG\\OneDrive\\Documentos\\PROJETO INTEGRADOR 1\\dados\\2nd_2023"

first_df_2023 = pd.read_csv(first_path2023, index_col=0)
second_df_2023 = pd.read_csv(first_path2023, index_col=0)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_23972\41015156.py:7: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  first_df_2023 = pd.read_csv(first_path2023, index_col=0)
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_23972\41015156.py:8: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  second_df_2023 = pd.read_csv(first_path2023, index_col=0)

In [11]:
# dados de 2024
# 2024 data

first_path2024 = "C:\\Users\\SAMSUNG\\OneDrive\\Documentos\\PROJETO INTEGRADOR 1\\dados\\1st_2024"  
second_path2024 = "C:\\Users\\SAMSUNG\\OneDrive\\Documentos\\PROJETO INTEGRADOR 1\\dados\\2nd_2024"

first_df_2024 = pd.read_csv(first_path2024, index_col=0)
second_df_2024 = pd.read_csv(first_path2024, index_col=0)

In [12]:
first_df_2024

,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESCR_SUBTIPOLOCAL,...,LONGITUDE,NOME_DELEGACIA_CIRCUNSCRIÇÃO,NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO,NOME_SECCIONAL_CIRCUNSCRIÇÃO,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA
NOME_DEPARTAMENTO,,,,,,,,,,,,,,,,,,,,,
DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AB8192,2024,2024-01-02,2023-12-28,23:55:00,NaN,Casa,...,0.000000,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2024
DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,AA0650,2024,2024-01-01,2024-01-01,NaN,De madrugada,Via Pública,...,NaN,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2024
DECAP,DEL.SEC.4º NORTE,13º D.P. CASA VERDE,S.PAULO,AA1075,2024,2024-01-01,2023-12-31,23:00:00,NaN,Transeunte,...,-46.634047,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Transeunte,FURTO - OUTROS,1,2024
DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,AA1444,2024,2024-01-01,2023-12-31,23:00:00,NaN,Via Pública,...,-46.625743,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Interior de Veículo,FURTO - OUTROS,1,2024
DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,AA4651,2024,2024-01-01,2023-12-31,NaN,A tarde,Metroviário e Ferroviário Metropolitano,...,NaN,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IR7765,2024,2024-06-25,2024-06-25,12:58:42,NaN,Via Pública,...,-46.795586,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IS4320,2024,2024-06-26,2024-06-25,20:40:00,NaN,Via Pública,...,-46.788974,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU0529,2024,2024-06-27,2024-06-27,03:13:00,NaN,Via Pública,...,-46.794137,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU3825,2024,2024-06-27,2024-06-27,09:40:00,NaN,Via Pública,...,-46.789868,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8115,2024,2024-06-27,2024-06-27,13:27:44,NaN,Via Pública,...,-46.805860,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024

# MERGE

In [15]:
# junção dos dados
# data merging

list_df = [first_df_2022_renamed, second_df_2022_renamed, first_df_2023, second_df_2023, first_df_2024, second_df_2024]
df_merged = pd.concat(list_df, axis=0)
df_merged

,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESCR_SUBTIPOLOCAL,...,LONGITUDE,NOME_DELEGACIA_CIRCUNSCRIÇÃO,NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO,NOME_SECCIONAL_CIRCUNSCRIÇÃO,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA
NOME_DEPARTAMENTO,,,,,,,,,,,,,,,,,,,,,
DECAP,DEL.SEC.8º SAO MATEUS,08ª DDM SAO MATEUS,S.PAULO,AC0851,2022,2022-01-13,2021-09-01 00:00:00,NaN,EM HORA INCERTA,Residência,...,0.000000,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Art. 213 - Estupro,NaN,ESTUPRO,1,2022
DECAP,DEL.SEC.8º SAO MATEUS,54º D.P. CID. TIRADENTES,S.PAULO,4,2022,2022-01-03,2021-12-31 00:00:00,15:20:00,NaN,Via pública,...,-46.632520,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.5º LESTE,29º D.P. VILA PRUDENTE,S.PAULO,7,2022,2022-01-04,2021-12-30 00:00:00,NaN,EM HORA INCERTA,Terminal/Estação,...,-46.631091,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),TRANSEUNTE,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,16:00:00,NaN,Via pública,...,-46.625872,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.1º CENTRO,06º D.P. CAMBUCI,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,13:30:00,NaN,Via pública,...,-46.630224,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IR7765,2024,2024-06-25,2024-06-25,12:58:42,NaN,Via Pública,...,-46.795586,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IS4320,2024,2024-06-26,2024-06-25,20:40:00,NaN,Via Pública,...,-46.788974,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU0529,2024,2024-06-27,2024-06-27,03:13:00,NaN,Via Pública,...,-46.794137,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU3825,2024,2024-06-27,2024-06-27,09:40:00,NaN,Via Pública,...,-46.789868,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8115,2024,2024-06-27,2024-06-27,13:27:44,NaN,Via Pública,...,-46.805860,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024

In [16]:
# normalizando "desc"
# normalizing "desc"

df = df_merged.rename(columns={'DESCR_SUBTIPOLOCAL': 'DESC_SUBTIPOLOCAL'})
df

,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESC_SUBTIPOLOCAL,...,LONGITUDE,NOME_DELEGACIA_CIRCUNSCRIÇÃO,NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO,NOME_SECCIONAL_CIRCUNSCRIÇÃO,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA
NOME_DEPARTAMENTO,,,,,,,,,,,,,,,,,,,,,
DECAP,DEL.SEC.8º SAO MATEUS,08ª DDM SAO MATEUS,S.PAULO,AC0851,2022,2022-01-13,2021-09-01 00:00:00,NaN,EM HORA INCERTA,Residência,...,0.000000,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Art. 213 - Estupro,NaN,ESTUPRO,1,2022
DECAP,DEL.SEC.8º SAO MATEUS,54º D.P. CID. TIRADENTES,S.PAULO,4,2022,2022-01-03,2021-12-31 00:00:00,15:20:00,NaN,Via pública,...,-46.632520,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.5º LESTE,29º D.P. VILA PRUDENTE,S.PAULO,7,2022,2022-01-04,2021-12-30 00:00:00,NaN,EM HORA INCERTA,Terminal/Estação,...,-46.631091,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),TRANSEUNTE,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,16:00:00,NaN,Via pública,...,-46.625872,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.1º CENTRO,06º D.P. CAMBUCI,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,13:30:00,NaN,Via pública,...,-46.630224,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IR7765,2024,2024-06-25,2024-06-25,12:58:42,NaN,Via Pública,...,-46.795586,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IS4320,2024,2024-06-26,2024-06-25,20:40:00,NaN,Via Pública,...,-46.788974,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU0529,2024,2024-06-27,2024-06-27,03:13:00,NaN,Via Pública,...,-46.794137,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU3825,2024,2024-06-27,2024-06-27,09:40:00,NaN,Via Pública,...,-46.789868,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8115,2024,2024-06-27,2024-06-27,13:27:44,NaN,Via Pública,...,-46.805860,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024

# SAVE

In [17]:
df.to_csv("C:\\Users\\SAMSUNG\\OneDrive\\Documentos\\PROJETO INTEGRADOR 1\\dados\\df_merged", index=False)