# LIBS

In [1]:
import pandas as pd
from google.colab import drive

# IMPORT

In [2]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [9]:
# dados de 2022

first_path2022  = "/content/drive/My Drive/projeto-integrador-I/data/raw/1st_2022.xlsx"
second_path2022 = "/content/drive/My Drive/projeto-integrador-I/data/raw/2nd_2022.xlsx"

first_df_2022  = pd.read_csv(first_path2022, index_col=0)
second_df_2022 = pd.read_csv(first_path2022, index_col=0)

/tmp/ipykernel_22391/653454469.py:6: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  first_df_2022  = pd.read_csv(first_path2022, index_col=0)
/tmp/ipykernel_22391/653454469.py:7: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  second_df_2022 = pd.read_csv(first_path2022, index_col=0)

In [10]:
''' 
    em analise explorativa, notou-se que algumas colunas
    mantiveram suas features, mas foram renomeadas a partir
    de 2023, gerando uma incoerências do ano de 2022 com os
    restantes:
     
    cidade de ocorrencia deixou de ser nomeada como "CIDADE"
    e passou a ser nomeada como "NOME_MUNICIPIO";

    data de registro deixou de ser nemada como
    "DATA_COMUNICACAO_BO" e passou a ser nomeada
    como "DATA_REGISTRO";

    descrição de periodo de ocorrencia deicou de ser nomeada
    como "DESCR_PERIODO" e passou a ser nomeada como
    "DESC_PERIODO".

    descrição do local de ocorrencia deixou de ser nomeada
    como "DESCR_TIPOLOCAL e passou a ser nomeada como
    "DESCR_SUBTIPOLOCAL".
'''

# renomando as colunas de 2022
# renaming 2022 columns

first_df_2022_renamed  = first_df_2022.rename(columns={'CIDADE': 'NOME_MUNICIPIO',
                                                      'DATA_COMUNICACAO_BO': 'DATA_REGISTRO',
                                                      "DESCR_PERIODO": "DESC_PERIODO",
                                                      "DESCR_TIPOLOCAL": "DESCR_SUBTIPOLOCAL"})

second_df_2022_renamed = second_df_2022.rename(columns={'CIDADE': 'NOME_MUNICIPIO',
                                                      'DATA_COMUNICACAO_BO': 'DATA_REGISTRO',
                                                      "DESCR_PERIODO": "DESC_PERIODO",
                                                      "DESCR_TIPOLOCAL": "DESCR_SUBTIPOLOCAL"})

In [11]:
# dados de 2023

first_path2023  = "/content/drive/My Drive/projeto-integrador-I/data/raw/1st_2023.xlsx"
second_path2023 = "/content/drive/My Drive/projeto-integrador-I/data/raw/2nd_2023.xlsx"

first_df_2023  = pd.read_csv(first_path2023, index_col=0)
second_df_2023 = pd.read_csv(first_path2023, index_col=0)

/tmp/ipykernel_22391/3622314882.py:6: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  first_df_2023  = pd.read_csv(first_path2023, index_col=0)
/tmp/ipykernel_22391/3622314882.py:7: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  second_df_2023 = pd.read_csv(first_path2023, index_col=0)

In [12]:
# dados de 2024

first_path2024  = "/content/drive/My Drive/projeto-integrador-I/data/raw/1st_2024.xlsx"
second_path2024 = "/content/drive/My Drive/projeto-integrador-I/data/raw/2nd_2024.xlsx"

first_df_2024  = pd.read_csv(first_path2024, index_col=0)
second_df_2024 = pd.read_csv(first_path2024, index_col=0)

In [13]:
# dados de 2025

first_path2025  = "/content/drive/My Drive/projeto-integrador-I/data/raw/1st_2025.xlsx"
second_path2025 = "/content/drive/My Drive/projeto-integrador-I/data/raw/2nd_2025.xlsx"

first_df_2025  = pd.read_csv(first_path2025, index_col=0)
second_df_2025 = pd.read_csv(first_path2025, index_col=0)

/tmp/ipykernel_22391/3589937457.py:6: DtypeWarning: Columns (15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  first_df_2025  = pd.read_csv(first_path2025, index_col=0)
/tmp/ipykernel_22391/3589937457.py:7: DtypeWarning: Columns (15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  second_df_2025 = pd.read_csv(first_path2025, index_col=0)

In [14]:
second_df_2025

,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESCR_TIPOLOCAL,...,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA,CMD,BTL,CIA
NOME_DEPARTAMENTO,,,,,,,,,,,,,,,,,,,,,
DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AA2328,2025,2025-01-01,2024-12-31,18:00:00,NaN,Comércio e Serviços,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AM7136,2025,2025-01-10,2025-01-10,00:00:00,NaN,Via Pública,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AQ9561,2025,2025-01-14,2025-01-14,NaN,Em hora incerta,Residência,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
DECAP,DEL.SEC.6º SANTO AMARO,06ª DDM SANTO AMARO,S.PAULO,BH3385,2025,2025-01-27,2025-01-25,18:00:14,NaN,Hospedagem,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,AA1448,2025,2025-01-01,2024-12-31,10:30:00,NaN,Via Pública,...,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IO7458,2025,2025-06-12,2025-06-12,19:00:00,NaN,Via Pública,...,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,CPA/M8,36ºBPM/M,2ªCIA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8903,2025,2025-06-17,2025-06-17,16:00:00,NaN,Via Pública,...,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,CPA/M8,36ºBPM/M,2ªCIA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IX5583,2025,2025-06-19,2025-06-19,14:00:00,NaN,Via Pública,...,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,CPA/M8,36ºBPM/M,2ªCIA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,JC6010,2025,2025-06-24,2025-06-24,11:00:59,NaN,Via Pública,...,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,CPA/M8,36ºBPM/M,2ªCIA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. EMBU DAS ARTES,EMBU DAS ARTES,JF1547,2025,2025-06-26,2025-06-26,09:50:00,NaN,Via Pública,...,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,CPA/M8,36ºBPM/M,2ªCIA

In [23]:
# o ano de 2025 tem 3 colunas a mais (cmd, ctl, cia)
df2025 = pd.concat([first_df_2025, second_df_2025], axis=0)
df2025 = df2025.drop(columns=['CMD', 'BTL', 'CIA'], axis=1) # remover para o merge
df2025.tail()

,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESCR_TIPOLOCAL,...,LONGITUDE,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA
NOME_DEPARTAMENTO,,,,,,,,,,,,,,,,,,,,,
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IO7458,2025,2025-06-12,2025-06-12,19:00:00,NaN,Via Pública,...,-46.786183,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8903,2025,2025-06-17,2025-06-17,16:00:00,NaN,Via Pública,...,-46.797775,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IX5583,2025,2025-06-19,2025-06-19,14:00:00,NaN,Via Pública,...,-46.796994,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,JC6010,2025,2025-06-24,2025-06-24,11:00:59,NaN,Via Pública,...,-46.788974,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. EMBU DAS ARTES,EMBU DAS ARTES,JF1547,2025,2025-06-26,2025-06-26,09:50:00,NaN,Via Pública,...,-46.804309,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025

In [42]:
first_df_2025['DESCR_TIPOLOCAL']

NOME_DEPARTAMENTO
DECAP                            Comércio e Serviços
DECAP                                    Via Pública
DECAP                                     Residência
DECAP                                     Hospedagem
DIPOL - DEPTO DE INTELIGENCIA            Via Pública
                                        ...
DEMACRO                                  Via Pública
DEMACRO                                  Via Pública
DEMACRO                                  Via Pública
DEMACRO                                  Via Pública
DEMACRO                                  Via Pública
Name: DESCR_TIPOLOCAL, Length: 585427, dtype: object

In [44]:
first_df_2025['DESCR_SUBTIPOLOCAL']

NOME_DEPARTAMENTO
DECAP                                Mercado
DECAP                            Via Pública
DECAP                                   Casa
DECAP                                  Motel
DIPOL - DEPTO DE INTELIGENCIA    Via Pública
                                    ...
DEMACRO                          Via Pública
DEMACRO                          Via Pública
DEMACRO                          Via Pública
DEMACRO                          Via Pública
DEMACRO                          Via Pública
Name: DESCR_SUBTIPOLOCAL, Length: 585427, dtype: object

In [35]:
print(len(first_df_2024.columns), len(df2025.columns))

24 25

# MERGE

In [24]:
# junção dos dados

list_df = [first_df_2022_renamed, second_df_2022_renamed, 
           first_df_2023, second_df_2023, 
           df2025]

df_merged = pd.concat(list_df, axis=0)
df_merged.tail()

,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESCR_SUBTIPOLOCAL,...,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA,DESCR_TIPOLOCAL,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO
NOME_DEPARTAMENTO,,,,,,,,,,,,,,,,,,,,,
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IO7458,2025,2025-06-12,2025-06-12,19:00:00,NaN,Via Pública,...,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,Via Pública,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8903,2025,2025-06-17,2025-06-17,16:00:00,NaN,Via Pública,...,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,Via Pública,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IX5583,2025,2025-06-19,2025-06-19,14:00:00,NaN,Via Pública,...,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,Via Pública,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,JC6010,2025,2025-06-24,2025-06-24,11:00:59,NaN,Via Pública,...,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,Via Pública,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. EMBU DAS ARTES,EMBU DAS ARTES,JF1547,2025,2025-06-26,2025-06-26,09:50:00,NaN,Via Pública,...,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,Via Pública,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA

In [ ]:
# normalizando "desc"

df = df_merged.rename(columns={'DESCR_SUBTIPOLOCAL': 'DESC_SUBTIPOLOCAL'})
df

,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESC_SUBTIPOLOCAL,...,LONGITUDE,NOME_DELEGACIA_CIRCUNSCRIÇÃO,NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO,NOME_SECCIONAL_CIRCUNSCRIÇÃO,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA
NOME_DEPARTAMENTO,,,,,,,,,,,,,,,,,,,,,
DECAP,DEL.SEC.8º SAO MATEUS,08ª DDM SAO MATEUS,S.PAULO,AC0851,2022,2022-01-13,2021-09-01 00:00:00,NaN,EM HORA INCERTA,Residência,...,0.000000,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Art. 213 - Estupro,NaN,ESTUPRO,1,2022
DECAP,DEL.SEC.8º SAO MATEUS,54º D.P. CID. TIRADENTES,S.PAULO,4,2022,2022-01-03,2021-12-31 00:00:00,15:20:00,NaN,Via pública,...,-46.632520,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.5º LESTE,29º D.P. VILA PRUDENTE,S.PAULO,7,2022,2022-01-04,2021-12-30 00:00:00,NaN,EM HORA INCERTA,Terminal/Estação,...,-46.631091,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),TRANSEUNTE,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,16:00:00,NaN,Via pública,...,-46.625872,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
DECAP,DEL.SEC.1º CENTRO,06º D.P. CAMBUCI,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,13:30:00,NaN,Via pública,...,-46.630224,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IR7765,2024,2024-06-25,2024-06-25,12:58:42,NaN,Via Pública,...,-46.795586,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IS4320,2024,2024-06-26,2024-06-25,20:40:00,NaN,Via Pública,...,-46.788974,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU0529,2024,2024-06-27,2024-06-27,03:13:00,NaN,Via Pública,...,-46.794137,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU3825,2024,2024-06-27,2024-06-27,09:40:00,NaN,Via Pública,...,-46.789868,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024
DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8115,2024,2024-06-27,2024-06-27,13:27:44,NaN,Via Pública,...,-46.805860,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2024

# SAVE

In [ ]:
df.to_csv("/content/drive/My Drive/projeto-integrador-I/data/processed/df_merged.csv", index=False)