# libs

In [1]:
import pandas as pd
from google.colab import drive

# import dos dados

In [2]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [3]:
df_path = "/content/drive/My Drive/projeto-integrador-I/data/processed/df_merged.csv"
df = pd.read_csv(df_path, index_col=0)

df

/tmp/ipykernel_24486/1294664248.py:2: DtypeWarning: Columns (12,13,14,15,16,17,18,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(df_path, index_col=0)

,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESC_SUBTIPOLOCAL,BAIRRO,...,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO
NOME_SECCIONAL,,,,,,,,,,,,,,,,,,,,,
DEL.SEC.8º SAO MATEUS,08ª DDM SAO MATEUS,S.PAULO,AC0851,2022,2022-01-13,2021-09-01 00:00:00,NaN,EM HORA INCERTA,Residência,SE,...,S.PAULO,Art. 213 - Estupro,NaN,ESTUPRO,1,2022,NaN,NaN,NaN,NaN
DEL.SEC.8º SAO MATEUS,54º D.P. CID. TIRADENTES,S.PAULO,4,2022,2022-01-03,2021-12-31 00:00:00,15:20:00,NaN,Via pública,Centro Histórico de São Paulo,...,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022,NaN,NaN,NaN,NaN
DEL.SEC.5º LESTE,29º D.P. VILA PRUDENTE,S.PAULO,7,2022,2022-01-04,2021-12-30 00:00:00,NaN,EM HORA INCERTA,Terminal/Estação,SE,...,S.PAULO,Furto (art. 155),TRANSEUNTE,FURTO - OUTROS,1,2022,NaN,NaN,NaN,NaN
DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,16:00:00,NaN,Via pública,Liberdade,...,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022,NaN,NaN,NaN,NaN
DEL.SEC.1º CENTRO,06º D.P. CAMBUCI,S.PAULO,8,2022,2022-01-03,2022-01-03 00:00:00,13:30:00,NaN,Via pública,LIBERDADE,...,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1,2022,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IO7458,2025,2025-06-12,2025-06-12,19:00:00,NaN,Via Pública,JARDIM SAPORITO,...,NaN,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IU8903,2025,2025-06-17,2025-06-17,16:00:00,NaN,Via Pública,J FREITAS JR,...,NaN,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,IX5583,2025,2025-06-19,2025-06-19,14:00:00,NaN,Via Pública,JARDIM FREITAS JUNIOR,...,NaN,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,TABOAO DA SERRA,JC6010,2025,2025-06-24,2025-06-24,11:00:59,NaN,Via Pública,J S SALVADOR,...,NaN,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,01º D.P. EMBU DAS ARTES,EMBU DAS ARTES,JF1547,2025,2025-06-26,2025-06-26,09:50:00,NaN,Via Pública,P JACARANDA,...,NaN,"tráfico drogas (Art.33, caput)",NaN,TRÁFICO DE ENTORPECENTES,6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA

# limpeza

In [ ]:
# exluindo colunas desnescessárias para o estudo

del_columns = [
    'NOME_DEPARTAMENTO', 
    'LATITUDE', 
    'NOME_SECCIONAL', 
    'LONGITUDE', 
    'NOME_DELEGACIA', 
    'NOME_DELEGACIA_CIRCUNSCRIÇÃO', 
    'NUM_BO', 
    'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO',
    'ANO_BO', 
    'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 
    'LOGRADOURO', 
    'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 
    'NUMERO_LOGRADOURO', 
    'DESCR_CONDUTA',
    'NATUREZA_APURADA'
]

df_col = df.drop(columns=[col for col in del_columns if col in df.columns])
df_col

,NOME_MUNICIPIO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESC_SUBTIPOLOCAL,BAIRRO,RUBRICA,MES_ESTATISTICA,ANO_ESTATISTICA,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO
NOME_SECCIONAL,,,,,,,,,,,,,,
DEL.SEC.8º SAO MATEUS,S.PAULO,2022-01-13,2021-09-01 00:00:00,NaN,EM HORA INCERTA,Residência,SE,Art. 213 - Estupro,1,2022,NaN,NaN,NaN,NaN
DEL.SEC.8º SAO MATEUS,S.PAULO,2022-01-03,2021-12-31 00:00:00,15:20:00,NaN,Via pública,Centro Histórico de São Paulo,Furto (art. 155),1,2022,NaN,NaN,NaN,NaN
DEL.SEC.5º LESTE,S.PAULO,2022-01-04,2021-12-30 00:00:00,NaN,EM HORA INCERTA,Terminal/Estação,SE,Furto (art. 155),1,2022,NaN,NaN,NaN,NaN
DEL.SEC.1º CENTRO,S.PAULO,2022-01-03,2022-01-03 00:00:00,16:00:00,NaN,Via pública,Liberdade,Furto (art. 155),1,2022,NaN,NaN,NaN,NaN
DEL.SEC.1º CENTRO,S.PAULO,2022-01-03,2022-01-03 00:00:00,13:30:00,NaN,Via pública,LIBERDADE,Furto (art. 155),1,2022,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,2025-06-12,2025-06-12,19:00:00,NaN,Via Pública,JARDIM SAPORITO,"tráfico drogas (Art.33, caput)",6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,2025-06-17,2025-06-17,16:00:00,NaN,Via Pública,J FREITAS JR,"tráfico drogas (Art.33, caput)",6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,2025-06-19,2025-06-19,14:00:00,NaN,Via Pública,JARDIM FREITAS JUNIOR,"tráfico drogas (Art.33, caput)",6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA,2025-06-24,2025-06-24,11:00:59,NaN,Via Pública,J S SALVADOR,"tráfico drogas (Art.33, caput)",6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
DEL.SEC.TABOÃO DA SERRA,EMBU DAS ARTES,2025-06-26,2025-06-26,09:50:00,NaN,Via Pública,P JACARANDA,"tráfico drogas (Art.33, caput)",6,2025,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA

In [ ]:
# filtrando os dados de santos

def city_filter(df, col, city):
    df[col] = df[col].str.strip().str.upper()

    return df[df[col] == city]

df_city = city_filter(df_col, "NOME_MUNICIPIO", "SANTOS")

df_city

,NOME_MUNICIPIO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESC_SUBTIPOLOCAL,BAIRRO,RUBRICA,MES_ESTATISTICA,ANO_ESTATISTICA,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO
NOME_SECCIONAL,,,,,,,,,,,,,,
DEL.SEC.SANTOS,SANTOS,2022-01-16,2022-01-16 00:00:00,13:00:00,NaN,Via pública,VILA JOQUEI CLUBE,Roubo (art. 157),1,2022,NaN,NaN,NaN,NaN
DEL.SEC.SANTOS,SANTOS,2022-01-11,2021-12-19 00:00:00,22:40:00,NaN,Internet,BOA VISTA,"Furto qualificado (art. 155, §4o.)",1,2022,NaN,NaN,NaN,NaN
DELEGACIA ELETRONICA,SANTOS,2022-01-13,2022-01-12 00:00:00,17:40:00,NaN,Via Pública,ALEMOA,Roubo (art. 157),1,2022,NaN,NaN,NaN,NaN
DELEGACIA ELETRONICA,SANTOS,2022-01-19,2021-12-07 00:00:00,10:15:00,NaN,Via Pública,ALEMOA,Roubo (art. 157),1,2022,NaN,NaN,NaN,NaN
DEL.SEC.SANTOS,SANTOS,2022-01-06,2022-01-06 00:00:00,NaN,PELA MANHÃ,Via pública,CENTRO,Furto de coisa comum (art. 156),1,2022,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DELEGACIA ELETRONICA,SANTOS,2025-06-19,2025-06-06,NaN,A noite,Outros,OUTEIRINHOS,Furto (art. 155),6,2025,DOPE - 05ª DP PORTO DE SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DIV.POL.PORTO/AERO/PROT.TURISTA,SANTOS,2025-06-24,2025-06-21,12:00:00,NaN,Portuário,OUTEIRINHOS,Furto (art. 155),6,2025,DOPE - 05ª DP PORTO DE SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DELEGACIA ELETRONICA,SANTOS,2025-06-24,2025-06-23,18:20:00,NaN,Via Pública,PORTO PAQUETA,Lesão corporal culposa na direção de veículo a...,6,2025,DOPE - 05ª DP PORTO DE SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DELEGACIA ELETRONICA,SANTOS,2025-06-26,2025-06-25,11:40:00,NaN,Via Pública,OUTEIRINHOS,Roubo (art. 157),6,2025,DOPE - 05ª DP PORTO DE SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DEL.SEC.PRAIA GRANDE,SANTOS,2025-06-18,2025-06-18,01:11:00,NaN,Via Pública,CENTRO,Roubo (art. 157),6,2025,DOPE - 05ª DP PORTO DE SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS

In [ ]:
# filtrando ocorrencias de estupro

df_occ = df_city[(df_city['RUBRICA'].str.upper().str.contains("ESTUPRO", regex=False, na=False, case=False))]
df_occ

,NOME_MUNICIPIO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,DESC_SUBTIPOLOCAL,BAIRRO,RUBRICA,MES_ESTATISTICA,ANO_ESTATISTICA,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO
NOME_SECCIONAL,,,,,,,,,,,,,,
DEL.SEC.PRAIA GRANDE,SANTOS,2022-01-05,2021-11-20 00:00:00,21:00:00,NaN,Comércio e Serviços,VILA MATIAS,Art. 213 - Estupro,1,2022,NaN,NaN,NaN,NaN
DEL.SEC.SANTOS,SANTOS,2022-01-09,2022-01-09 00:00:00,00:07:39,NaN,Residência,MARAPE,Estupro de vulneravel (art.217-A),1,2022,NaN,NaN,NaN,NaN
DEL.SEC.SANTOS,SANTOS,2022-01-16,2022-01-15 00:00:00,19:30:27,NaN,Residência,MACUCO,Art. 213 - Estupro,1,2022,NaN,NaN,NaN,NaN
DEL.SEC.SANTOS,SANTOS,2022-01-11,NaN,NaN,EM HORA INCERTA,Residência,MORRO NOVA CINTRA,Estupro de vulneravel (art.217-A),1,2022,NaN,NaN,NaN,NaN
DEL.SEC.SANTOS,SANTOS,2022-02-05,2021-10-17 00:00:00,NaN,DE MADRUGADA,Via Pública,MACUCO,Art. 213 - Estupro,2,2022,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEL.SEC.SANTOS,SANTOS,2025-06-09,2025-03-15,NaN,A noite,Apartamento,SABOO,Estupro - Art. 213,6,2025,05º D.P. SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DEL.SEC.SANTOS,SANTOS,2025-06-18,2024-08-30,NaN,Em hora incerta,Casa,CASTELO,Estupro - Art. 213,6,2025,05º D.P. SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DEL.SEC.SANTOS,SANTOS,2025-06-02,2025-06-02,NaN,A tarde,Casa,CHICO DE PAULA,Estupro de vulneravel (art.217-A),6,2025,05º D.P. SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DEL.SEC.SANTOS,SANTOS,2025-06-17,2022-12-15,NaN,A noite,Casas,PIRATININGA,Estupro de vulneravel (art.217-A),6,2025,05º D.P. SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS
DEL.SEC.SANTOS,SANTOS,2025-06-18,2025-06-18,05:10:00,NaN,Via Pública,JOSÉ MENINO,Estupro - Art. 213,6,2025,07º D.P. SANTOS,DEINTER 6 - SANTOS,DEL.SEC.SANTOS,SANTOS

# save

In [7]:
df_occ.to_csv("/content/drive/My Drive/projeto-integrador-I/data/processed/df_cleaned.csv", index=False)