# libs e dados

In [15]:
import pandas as pd
import numpy as np
from google.colab import drive

In [16]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [17]:
delta = pd.read_csv('/content/drive/MyDrive/projeto-integrador-I/data/processed/delta_table.csv')
delta.head()

   Unnamed: 0  count
0           0     68
1           1     44
2           2     22
3           3     10
4          10      6

In [18]:
delta = delta.rename(columns={"Unnamed: 0": "delta"})
delta.head()

   delta  count
0      0     68
1      1     44
2      2     22
3      3     10
4     10      6

# tabela de frequencia

In [19]:
# classes da tabela
k = int(np.ceil(1 +  3.3 * np.log10(len(delta)))) # regra de sturges

In [20]:
# classes com amplitude variável
delta['classe'] = pd.qcut(delta['delta'], q=k, duplicates='drop')

# tabela inicial com frequencia de classe
freq = delta.groupby('classe', observed=False)['count'].sum().reset_index()
freq.columns = ['_intervalo', 'fi'] # _intervalo é apenas um suporte para os proximos calculos
freq.head()

           _intervalo   fi
0     (-0.001, 7.571]  158
1     (7.571, 27.143]   28
2    (27.143, 44.571]   22
3   (44.571, 111.571]   22
4  (111.571, 470.143]   18

In [21]:
# classes da tabela
freq['intervalos'] = freq['_intervalo'].apply(
    lambda x: f"{int(x.left)} |- {int(x.right)}"
)

freq

            _intervalo   fi    intervalos
0      (-0.001, 7.571]  158        0 |- 7
1      (7.571, 27.143]   28       7 |- 27
2     (27.143, 44.571]   22      27 |- 44
3    (44.571, 111.571]   22     44 |- 111
4   (111.571, 470.143]   18    111 |- 470
5  (470.143, 1618.429]   20   470 |- 1618
6   (1618.429, 7057.0]   24  1618 |- 7057

In [22]:
# classes medias (xi)
freq['xi'] = freq['_intervalo'].apply(
    lambda x: float((x.left + x.right) / 2)
).round(1)

freq

            _intervalo   fi    intervalos         xi
0      (-0.001, 7.571]  158        0 |- 7     3.7850
1      (7.571, 27.143]   28       7 |- 27    17.3570
2     (27.143, 44.571]   22      27 |- 44    35.8570
3    (44.571, 111.571]   22     44 |- 111    78.0710
4   (111.571, 470.143]   18    111 |- 470   290.8570
5  (470.143, 1618.429]   20   470 |- 1618  1044.2860
6   (1618.429, 7057.0]   24  1618 |- 7057  4337.7145

In [23]:
# produto medio
freq['xifi'] = freq['xi'].astype(float) * freq['fi'].astype(float)
freq

            _intervalo   fi    intervalos         xi        xifi
0      (-0.001, 7.571]  158        0 |- 7     3.7850     598.030
1      (7.571, 27.143]   28       7 |- 27    17.3570     485.996
2     (27.143, 44.571]   22      27 |- 44    35.8570     788.854
3    (44.571, 111.571]   22     44 |- 111    78.0710    1717.562
4   (111.571, 470.143]   18    111 |- 470   290.8570    5235.426
5  (470.143, 1618.429]   20   470 |- 1618  1044.2860   20885.720
6   (1618.429, 7057.0]   24  1618 |- 7057  4337.7145  104105.148

In [24]:
# frequencia relativa(fr)
total = freq['fi'].sum()
freq['fr'] = freq['fi'] / total * 100
freq

            _intervalo   fi    intervalos         xi        xifi         fr
0      (-0.001, 7.571]  158        0 |- 7     3.7850     598.030  54.109589
1      (7.571, 27.143]   28       7 |- 27    17.3570     485.996   9.589041
2     (27.143, 44.571]   22      27 |- 44    35.8570     788.854   7.534247
3    (44.571, 111.571]   22     44 |- 111    78.0710    1717.562   7.534247
4   (111.571, 470.143]   18    111 |- 470   290.8570    5235.426   6.164384
5  (470.143, 1618.429]   20   470 |- 1618  1044.2860   20885.720   6.849315
6   (1618.429, 7057.0]   24  1618 |- 7057  4337.7145  104105.148   8.219178

In [25]:
# frequencia acumulada absoluta (fac)
freq['fac'] = freq['fi'].cumsum()
freq

,_intervalo,fi,intervalos,xi,xifi,fr,fac
0,"(-0.001, 7.571]",158,0 |- 7,3.7850,598.030,54.109589,158
1,"(7.571, 27.143]",28,7 |- 27,17.3570,485.996,9.589041,186
2,"(27.143, 44.571]",22,27 |- 44,35.8570,788.854,7.534247,208
3,"(44.571, 111.571]",22,44 |- 111,78.0710,1717.562,7.534247,230
4,"(111.571, 470.143]",18,111 |- 470,290.8570,5235.426,6.164384,248
5,"(470.143, 1618.429]",20,470 |- 1618,1044.2860,20885.720,6.849315,268
6,"(1618.429, 7057.0]",24,1618 |- 7057,4337.7145,104105.148,8.219178,292

In [26]:
# frequencia relativa acumulada (fri)
freq['fri'] = freq['fr'].cumsum()
freq

,_intervalo,fi,intervalos,xi,xifi,fr,fac,fri
0,"(-0.001, 7.571]",158,0 |- 7,3.7850,598.030,54.109589,158,54.109589
1,"(7.571, 27.143]",28,7 |- 27,17.3570,485.996,9.589041,186,63.698630
2,"(27.143, 44.571]",22,27 |- 44,35.8570,788.854,7.534247,208,71.232877
3,"(44.571, 111.571]",22,44 |- 111,78.0710,1717.562,7.534247,230,78.767123
4,"(111.571, 470.143]",18,111 |- 470,290.8570,5235.426,6.164384,248,84.931507
5,"(470.143, 1618.429]",20,470 |- 1618,1044.2860,20885.720,6.849315,268,91.780822
6,"(1618.429, 7057.0]",24,1618 |- 7057,4337.7145,104105.148,8.219178,292,100.000000

In [27]:
# tablea final organizada
table = freq[['intervalos', 'fi', 'xi', 'xifi', 'fr', 'fac', 'fri']].copy()
table = table.reset_index(drop=True)
table

     intervalos   fi         xi        xifi         fr  fac         fri
0        0 |- 7  158     3.7850     598.030  54.109589  158   54.109589
1       7 |- 27   28    17.3570     485.996   9.589041  186   63.698630
2      27 |- 44   22    35.8570     788.854   7.534247  208   71.232877
3     44 |- 111   22    78.0710    1717.562   7.534247  230   78.767123
4    111 |- 470   18   290.8570    5235.426   6.164384  248   84.931507
5   470 |- 1618   20  1044.2860   20885.720   6.849315  268   91.780822
6  1618 |- 7057   24  4337.7145  104105.148   8.219178  292  100.000000

In [28]:
table.to_excel('/content/drive/MyDrive/projeto-integrador-I/data/processed/freq_table.xlsx')

# estatisticas estimadas

In [29]:
# media estimada 
mean = int(table['xifi'].sum() / total)
mean

458

In [30]:
# traduzindo para um formato de calendario
mean_mounth = int(mean / 30)
mean_days   = mean % 30

mean_mounth, mean_days

(15, 8)

# tabela de frequencia da primeira semana

In [32]:
# ocorrencias notificadas dentro da primeira semana (até 7 dias)
week = delta[delta['delta'] <= 7].sort_values(by='delta')
week = week.drop(columns='classe')
week = week.rename(columns={'delta' : 'classe'})
week

    classe  count
0        0     68
1        1     44
2        2     22
3        3     10
48       4      2
37       5      2
5        6      6
24       7      4

In [33]:
# frequência de cada intervalo (fi)
week = week.rename(columns={'count' : 'fi'})
week

    classe  fi
0        0  68
1        1  44
2        2  22
3        3  10
48       4   2
37       5   2
5        6   6
24       7   4

In [34]:
# frequencia relativa (fr)
week_total = week['fi'].sum()
week['fr'] = week['fi'] / week_total * 100
week

    classe  fi         fr
0        0  68  43.037975
1        1  44  27.848101
2        2  22  13.924051
3        3  10   6.329114
48       4   2   1.265823
37       5   2   1.265823
5        6   6   3.797468
24       7   4   2.531646

In [35]:
# frequencia acumulada absoluta (fac)
week['fac'] = week['fi'].cumsum()
week

    classe  fi         fr  fac
0        0  68  43.037975   68
1        1  44  27.848101  112
2        2  22  13.924051  134
3        3  10   6.329114  144
48       4   2   1.265823  146
37       5   2   1.265823  148
5        6   6   3.797468  154
24       7   4   2.531646  158

In [36]:
# frequencia relativa acumulada (fri)
week['fri'] = week['fr'].cumsum()
week

    classe  fi         fr  fac         fri
0        0  68  43.037975   68   43.037975
1        1  44  27.848101  112   70.886076
2        2  22  13.924051  134   84.810127
3        3  10   6.329114  144   91.139241
48       4   2   1.265823  146   92.405063
37       5   2   1.265823  148   93.670886
5        6   6   3.797468  154   97.468354
24       7   4   2.531646  158  100.000000

In [37]:
week.to_excel('/content/drive/MyDrive/projeto-integrador-I/data/processed/week_table.xlsx')