# libs e dados

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Mounted at /content/drive/

In [3]:
delta = pd.read_csv('/content/drive/MyDrive/projeto-integrador-I/data/processed/delta_table.csv')
delta.head()

   Unnamed: 0  count
0           0     79
1           1     56
2           2     22
3           4     14
4           3     10

In [4]:
delta = delta.rename(columns={"Unnamed: 0": "delta"})
delta.head()

   delta  count
0      0     79
1      1     56
2      2     22
3      4     14
4      3     10

# tabela de frequencia

In [5]:
# classes da tabela
k = int(np.ceil(1 +  3.3 * np.log10(len(delta)))) # regra de sturges

In [6]:
# classes com amplitude variável
delta['classe'] = pd.qcut(delta['delta'], q=k, duplicates='drop')

# tabela inicial com frequencia de classe
freq = delta.groupby('classe', observed=False)['count'].sum().reset_index()
freq.columns = ['_intervalo', 'fi'] # _intervalo é apenas um suporte para os proximos calculos
freq.head()

         _intervalo   fi
0  (-0.001, 13.625]  218
1   (13.625, 34.25]   21
2    (34.25, 67.75]   16
3    (67.75, 175.0]   14
4   (175.0, 439.25]   14

In [7]:
freq['intervalos'] = freq['_intervalo'].apply(
    lambda x: f"{x.left} |- {x.right}"
)

freq

           _intervalo   fi          intervalos
0    (-0.001, 13.625]  218    -0.001 |- 13.625
1     (13.625, 34.25]   21     13.625 |- 34.25
2      (34.25, 67.75]   16      34.25 |- 67.75
3      (67.75, 175.0]   14      67.75 |- 175.0
4     (175.0, 439.25]   14     175.0 |- 439.25
5   (439.25, 1002.25]   13   439.25 |- 1002.25
6  (1002.25, 2317.25]   15  1002.25 |- 2317.25
7   (2317.25, 7057.0]   14   2317.25 |- 7057.0

In [8]:
freq['xi'] = freq['_intervalo'].apply(
    lambda x: round(float((x.left + x.right) / 2), 1)
)

freq

           _intervalo   fi          intervalos      xi
0    (-0.001, 13.625]  218    -0.001 |- 13.625     6.8
1     (13.625, 34.25]   21     13.625 |- 34.25    23.9
2      (34.25, 67.75]   16      34.25 |- 67.75    51.0
3      (67.75, 175.0]   14      67.75 |- 175.0   121.4
4     (175.0, 439.25]   14     175.0 |- 439.25   307.1
5   (439.25, 1002.25]   13   439.25 |- 1002.25   720.8
6  (1002.25, 2317.25]   15  1002.25 |- 2317.25  1659.8
7   (2317.25, 7057.0]   14   2317.25 |- 7057.0  4687.1

In [9]:
# produto medio
freq['xifi'] = freq['xi'].astype(float) * freq['fi'].astype(float)
freq

           _intervalo   fi          intervalos      xi     xifi
0    (-0.001, 13.625]  218    -0.001 |- 13.625     6.8   1482.4
1     (13.625, 34.25]   21     13.625 |- 34.25    23.9    501.9
2      (34.25, 67.75]   16      34.25 |- 67.75    51.0    816.0
3      (67.75, 175.0]   14      67.75 |- 175.0   121.4   1699.6
4     (175.0, 439.25]   14     175.0 |- 439.25   307.1   4299.4
5   (439.25, 1002.25]   13   439.25 |- 1002.25   720.8   9370.4
6  (1002.25, 2317.25]   15  1002.25 |- 2317.25  1659.8  24897.0
7   (2317.25, 7057.0]   14   2317.25 |- 7057.0  4687.1  65619.4

In [10]:
# frequencia relativa(fr)
total = freq['fi'].sum()
freq['fr'] = freq['fi'] / total * 100
freq

           _intervalo   fi          intervalos      xi     xifi         fr
0    (-0.001, 13.625]  218    -0.001 |- 13.625     6.8   1482.4  67.076923
1     (13.625, 34.25]   21     13.625 |- 34.25    23.9    501.9   6.461538
2      (34.25, 67.75]   16      34.25 |- 67.75    51.0    816.0   4.923077
3      (67.75, 175.0]   14      67.75 |- 175.0   121.4   1699.6   4.307692
4     (175.0, 439.25]   14     175.0 |- 439.25   307.1   4299.4   4.307692
5   (439.25, 1002.25]   13   439.25 |- 1002.25   720.8   9370.4   4.000000
6  (1002.25, 2317.25]   15  1002.25 |- 2317.25  1659.8  24897.0   4.615385
7   (2317.25, 7057.0]   14   2317.25 |- 7057.0  4687.1  65619.4   4.307692

In [11]:
# frequencia acumulada absoluta (fac)
freq['fac'] = freq['fi'].cumsum()
freq

,_intervalo,fi,intervalos,xi,xifi,fr,fac
0,"(-0.001, 13.625]",218,-0.001 |- 13.625,6.8,1482.4,67.076923,218
1,"(13.625, 34.25]",21,13.625 |- 34.25,23.9,501.9,6.461538,239
2,"(34.25, 67.75]",16,34.25 |- 67.75,51.0,816.0,4.923077,255
3,"(67.75, 175.0]",14,67.75 |- 175.0,121.4,1699.6,4.307692,269
4,"(175.0, 439.25]",14,175.0 |- 439.25,307.1,4299.4,4.307692,283
5,"(439.25, 1002.25]",13,439.25 |- 1002.25,720.8,9370.4,4.000000,296
6,"(1002.25, 2317.25]",15,1002.25 |- 2317.25,1659.8,24897.0,4.615385,311
7,"(2317.25, 7057.0]",14,2317.25 |- 7057.0,4687.1,65619.4,4.307692,325

In [12]:
# frequencia relativa acumulada (fri)
freq['fri'] = freq['fr'].cumsum()
freq

,_intervalo,fi,intervalos,xi,xifi,fr,fac,fri
0,"(-0.001, 13.625]",218,-0.001 |- 13.625,6.8,1482.4,67.076923,218,67.076923
1,"(13.625, 34.25]",21,13.625 |- 34.25,23.9,501.9,6.461538,239,73.538462
2,"(34.25, 67.75]",16,34.25 |- 67.75,51.0,816.0,4.923077,255,78.461538
3,"(67.75, 175.0]",14,67.75 |- 175.0,121.4,1699.6,4.307692,269,82.769231
4,"(175.0, 439.25]",14,175.0 |- 439.25,307.1,4299.4,4.307692,283,87.076923
5,"(439.25, 1002.25]",13,439.25 |- 1002.25,720.8,9370.4,4.000000,296,91.076923
6,"(1002.25, 2317.25]",15,1002.25 |- 2317.25,1659.8,24897.0,4.615385,311,95.692308
7,"(2317.25, 7057.0]",14,2317.25 |- 7057.0,4687.1,65619.4,4.307692,325,100.000000

In [13]:
# tablea final organizada
table = freq[['intervalos', 'fi', 'xi', 'xifi', 'fr', 'fac', 'fri']].copy()
table = table.reset_index(drop=True)
table

           intervalos   fi      xi     xifi         fr  fac         fri
0    -0.001 |- 13.625  218     6.8   1482.4  67.076923  218   67.076923
1     13.625 |- 34.25   21    23.9    501.9   6.461538  239   73.538462
2      34.25 |- 67.75   16    51.0    816.0   4.923077  255   78.461538
3      67.75 |- 175.0   14   121.4   1699.6   4.307692  269   82.769231
4     175.0 |- 439.25   14   307.1   4299.4   4.307692  283   87.076923
5   439.25 |- 1002.25   13   720.8   9370.4   4.000000  296   91.076923
6  1002.25 |- 2317.25   15  1659.8  24897.0   4.615385  311   95.692308
7   2317.25 |- 7057.0   14  4687.1  65619.4   4.307692  325  100.000000

In [14]:
table.to_excel('/content/drive/MyDrive/projeto-integrador-I/data/processed/freq_table.xlsx')

# estatisticas estimadas

In [15]:
# media estimada
mean = int(table['xifi'].sum() / total)
mean

334

In [16]:
# traduzindo para um formato de calendario
mean_mounth = int(mean / 30)
mean_days   = mean % 30

mean_mounth, mean_days

(11, 4)

# tabela de frequencia da primeira semana

In [17]:
# ocorrencias notificadas dentro da primeira semana (até 7 dias)
week = delta[delta['delta'] <= 7].sort_values(by='delta')
week = week.drop(columns='classe')
week = week.rename(columns={'delta' : 'classe'})
week

    classe  count
0        0     79
1        1     56
2        2     22
4        3     10
3        4     14
5        5      6
10       6      3
9        7      4

In [18]:
# frequência de cada intervalo (fi)
week = week.rename(columns={'count' : 'fi'})
week

    classe  fi
0        0  79
1        1  56
2        2  22
4        3  10
3        4  14
5        5   6
10       6   3
9        7   4

In [19]:
# frequencia relativa (fr)
week_total = week['fi'].sum()
week['fr'] = week['fi'] / week_total * 100
week

    classe  fi         fr
0        0  79  40.721649
1        1  56  28.865979
2        2  22  11.340206
4        3  10   5.154639
3        4  14   7.216495
5        5   6   3.092784
10       6   3   1.546392
9        7   4   2.061856

In [20]:
# frequencia acumulada absoluta (fac)
week['fac'] = week['fi'].cumsum()
week

    classe  fi         fr  fac
0        0  79  40.721649   79
1        1  56  28.865979  135
2        2  22  11.340206  157
4        3  10   5.154639  167
3        4  14   7.216495  181
5        5   6   3.092784  187
10       6   3   1.546392  190
9        7   4   2.061856  194

In [21]:
# frequencia relativa acumulada (fri)
week['fri'] = week['fr'].cumsum()
week

    classe  fi         fr  fac         fri
0        0  79  40.721649   79   40.721649
1        1  56  28.865979  135   69.587629
2        2  22  11.340206  157   80.927835
4        3  10   5.154639  167   86.082474
3        4  14   7.216495  181   93.298969
5        5   6   3.092784  187   96.391753
10       6   3   1.546392  190   97.938144
9        7   4   2.061856  194  100.000000

In [22]:
week.to_excel('/content/drive/MyDrive/projeto-integrador-I/data/processed/week_table.xlsx')